networks:
  product-discount-network:
    driver: bridge

services:
  postgres:
    image: postgres:16
    container_name: product-discount-db
    environment:
      POSTGRES_ID: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init/sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - product-discount-network

  # Ktor product API Services
  product-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-discount-api
    environment:
      KTOR_DATABASE_JDBC_URL: "jdbc.postgresql://postgres:5432/productdb"
      KTOR_DATABASE_DRIVER: "org.postgresql.Driver"
      KTOR_DATABASE_USERNAME: "postgres"
      KTOR_DATABASE_PASSWORD: "postgres"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - product-discount-network

